IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'DSC')
BEGIN
CREATE DATABASE [DSC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DSC', FILENAME = N'{0}\DSC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DSC_log', FILENAME = N'{0}\DSC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
END

ALTER DATABASE [DSC] SET COMPATIBILITY_LEVEL = 140
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DSC].[dbo].[sp_fulltext_database] @action = 'enable'
end
ALTER DATABASE [DSC] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [DSC] SET ANSI_NULLS OFF 
ALTER DATABASE [DSC] SET ANSI_PADDING OFF 
ALTER DATABASE [DSC] SET ANSI_WARNINGS OFF 
ALTER DATABASE [DSC] SET ARITHABORT OFF 
ALTER DATABASE [DSC] SET AUTO_CLOSE ON 
ALTER DATABASE [DSC] SET AUTO_SHRINK OFF 
ALTER DATABASE [DSC] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [DSC] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [DSC] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [DSC] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [DSC] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [DSC] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [DSC] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [DSC] SET  ENABLE_BROKER 
ALTER DATABASE [DSC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [DSC] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [DSC] SET TRUSTWORTHY OFF 
ALTER DATABASE [DSC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [DSC] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [DSC] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [DSC] SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE [DSC] SET RECOVERY SIMPLE 
ALTER DATABASE [DSC] SET  MULTI_USER 
ALTER DATABASE [DSC] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [DSC] SET DB_CHAINING OFF 
ALTER DATABASE [DSC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
ALTER DATABASE [DSC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
ALTER DATABASE [DSC] SET DELAYED_DURABILITY = DISABLED 
ALTER DATABASE [DSC] SET QUERY_STORE = OFF
USE [DSC]
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
ALTER DATABASE [DSC] SET  READ_WRITE 

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Devices]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Devices](
	[TargetName] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TargetName] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ConfigurationID] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ServerCheckSum] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ServerCheckSum] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TargetCheckSum] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TargetCheckSum] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[NodeCompliant] [bit] NOT NULL,
	[NodeCompliant] [bit] NOT NULL,
	[LastComplianceTime] [datetime] NULL,
	[LastComplianceTime] [datetime] NULL,
	[LastHeartbeatTime] [datetime] NULL,
	[Dirty] [bit] NULL,
	[StatusCode] [int] NULL
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Devices__NodeCom__37A5467C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Devices] ADD  DEFAULT ((0)) FOR [NodeCompliant]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Devices__Dirty__38996AB5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Devices] ADD  DEFAULT ((1)) FOR [Dirty]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Devices__StatusC__398D8EEE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Devices] ADD  DEFAULT ((-1)) FOR [StatusCode]
END

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RegistrationData]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RegistrationData](
	[AgentId] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LCMVersion] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NodeName] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IPAddress] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConfigurationNames] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[StatusReport]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[StatusReport](
	[JobId] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Id] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OperationType] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RefreshMode] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LCMVersion] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportFormatVersion] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConfigurationVersion] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NodeName] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IPAddress] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StartTime] [datetime] NULL,
	[EndTime] [datetime] NULL,
	[Errors] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StatusData] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RebootRequested] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdditionalData] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__StatusRep__Start__3B75D760]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[StatusReport] ADD  DEFAULT (getdate()) FOR [StartTime]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__StatusRep__EndTi__3C69FB99]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[StatusReport] ADD  DEFAULT (getdate()) FOR [EndTime]
END
